parameters:
  - name: destroy
    type: boolean
    default: false
  - name: environments
    type: object
    default:
      - name: envName
        default: envName
      - name: dependsOn
        default: []
      - name: backendAzureRmResourceGroupName
        default: backendAzureRmResourceGroupName
      - name: backendAzureRmStorageAccountName
        default: backendAzureRmStorageAccountName
      - name: tfVarsFile
        default: 'tfVarsFile'
  - name: infrastructureGroups
    type: object
    default:
      - name: infrastructureName
        default: 'infrastructureName'
      - name: dependsOn
        default: []
      - name: deployOn
        default: []
      - name: workingDirectory
        default: 'workingDirectory'
      - name: backendAzureRmContainerName
        default: 'backendAzureRmContainerName'

stages:
  - ${{ each env in parameters.environments}}:
    - stage: ${{ env.envName }}
      dependsOn: ${{ env.dependsOn }}
      ${{ if env.dependsOn }}:
        condition: succeeded('${{ env.dependsOn }}')
      jobs: 
      - ${{ each infra in parameters.infrastructureGroups }}:
        ${{ if infra.deployOn }}:
          condition: ${{ containsValue(infra.deployOn, env.envName) }}
          - ${{ if parameters.destroy }}:  
              - template: ../../Jobs/Terraform/terraform-destroy-job.yml
                parameters:
                  name: ${{ infra.infrastructureName }}
                  workingDirectory: ${{ infra.workingDirectory }}
                  backendAzureRmResourceGroupName: ${{ env.backendAzureRmResourceGroupName }}
                  backendAzureRmStorageAccountName: ${{ env.backendAzureRmStorageAccountName }}
                  backendAzureRmContainerName: ${{ infra.backendAzureRmContainerName }}
                  planCommandOptions: '-var-file="EnvironmentVariables/${{ env.tfVarsFile }}"'
          - ${{ else }}:      
              - template: ../../Jobs/Terraform/terraform-apply-job.yml
                parameters:
                  name: ${{ infra.infrastructureName }}
                  workingDirectory: ${{ infra.workingDirectory }}
                  backendAzureRmResourceGroupName: ${{ env.backendAzureRmResourceGroupName }}
                  backendAzureRmStorageAccountName: ${{ env.backendAzureRmStorageAccountName }}
                  backendAzureRmContainerName: ${{ infra.backendAzureRmContainerName }}
                  planCommandOptions: '-var-file="EnvironmentVariables/${{ env.tfVarsFile }}"'        
