parameters:
  - name: destroy
    type: boolean
    default: false
  - name: planAdditionalOptions
    default: ''
  - name: environments
    type: object
    default:
      - name: envName
        default: envName
      - name: dependsOn
        default: []
      - name: backendAzureRmResourceGroupName
        default: backendAzureRmResourceGroupName
      - name: backendAzureRmStorageAccountName
        default: backendAzureRmStorageAccountName
      - name: tfVarsFile
        default: ''
      - name: planAdditionalOptions
        default: ''
  - name: infrastructureGroups
    type: object
    default:
      - name: infrastructureName
        default: 'infrastructureName'
      - name: dependsOn
        default: []
      - name: deployOn
        default: []
      - name: workingDirectory
        default: 'workingDirectory'
      - name: backendAzureRmContainerName
        default: 'backendAzureRmContainerName'
      - name: planAdditionalOptions
        default: ''

stages:
  - ${{ each env in parameters.environments}}:
    - stage: ${{ env.envName }}
      dependsOn: ${{ env.dependsOn }}
      ${{ if env.dependsOn }}:
        condition: and(succeeded('${{ env.dependsOn }}'), or(eq('${{ env.envName }}', 'dev'), eq(variables['Build.SourceBranch'], 'refs/heads/main')))
      ${{ else }}:
        condition: or(eq('${{ env.envName }}', 'dev'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      jobs:
      - ${{ each infra in parameters.infrastructureGroups }}:
        - ${{ if containsValue(infra.deployOn, env.envName) }}:
          - ${{ if parameters.destroy }}:
            - template: ../../Jobs/Terraform/terraform-destroy-job.yml
              parameters:
                name: ${{ infra.infrastructureName }}
                dependsOn: ${{ infra.dependsOn }}
                workingDirectory: ${{ infra.workingDirectory }}
                backendAzureRmResourceGroupName: ${{ env.backendAzureRmResourceGroupName }}
                backendAzureRmStorageAccountName: ${{ env.backendAzureRmStorageAccountName }}
                backendAzureRmContainerName: ${{ infra.backendAzureRmContainerName }}
                ${{ if eq('env.tfVarsFile', '')}}:
                  planCommandOptions: ${{ parameters.planAdditionalOptions }} ${{ infra.planAdditionalOptions }} ${{ env.planAdditionalOptions }}
                ${{ else }}:
                  planCommandOptions: -var-file="EnvironmentVariables/${{ env.tfVarsFile }}" ${{ parameters.planAdditionalOptions }} ${{ infra.planAdditionalOptions }} ${{ env.planAdditionalOptions }}
          - ${{ else }}:
            - template: ../../Jobs/Terraform/terraform-apply-job.yml
              parameters:
                name: ${{ infra.infrastructureName }}
                dependsOn: ${{ infra.dependsOn }}
                workingDirectory: ${{ infra.workingDirectory }}
                backendAzureRmResourceGroupName: ${{ env.backendAzureRmResourceGroupName }}
                backendAzureRmStorageAccountName: ${{ env.backendAzureRmStorageAccountName }}
                backendAzureRmContainerName: ${{ infra.backendAzureRmContainerName }}
                ${{ if eq('env.tfVarsFile', '')}}:
                  planCommandOptions: ${{ parameters.planAdditionalOptions }} ${{ infra.planAdditionalOptions }} ${{ env.planAdditionalOptions }}
                ${{ else }}:
                  planCommandOptions: -var-file="EnvironmentVariables/${{ env.tfVarsFile }}" ${{ parameters.planAdditionalOptions }} ${{ infra.planAdditionalOptions }} ${{ env.planAdditionalOptions }}
